//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Individualized.Education.Plan {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public enum GradeLevel {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6th")]
        Item6th,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7th")]
        Item7th,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8th")]
        Item8th,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public enum Gender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute("PrimaryDisability", Namespace="", IsNullable=false)]
    public enum Disability {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Orthopedic Impairment")]
        OrthopedicImpairment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Other Health Impairment")]
        OtherHealthImpairment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Auditory Impairment")]
        AuditoryImpairment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Visual Impairment")]
        VisualImpairment,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Deaf-Blind")]
        DeafBlind,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Intellectual Disability")]
        IntellectualDisability,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Emotional Disturbance")]
        EmotionalDisturbance,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Learning Disability")]
        LearningDisability,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Speech Impairment")]
        SpeechImpairment,
        
        /// <remarks/>
        Autism,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Developmental Delay")]
        DevelopmentalDelay,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Traumatic Brain Injury")]
        TraumaticBrainInjury,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class IndividualizedEducationPlan {
        
        /// <remarks/>
        public StudentData StudentData;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AccommodationCategory[] AccommodationsList;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PresentLevel[] PresentLevels;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StudentData {
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public Gender Gender;
        
        /// <remarks/>
        public GradeLevel GradeLevel;
        
        /// <remarks/>
        public Disability PrimaryDisability;
        
        /// <remarks/>
        public Disability SecondaryDisability;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondaryDisabilitySpecified;
        
        /// <remarks/>
        public Disability TertiaryDisability;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TertiaryDisabilitySpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccommodationCategory {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccommodationItem")]
        public AccommodationItem[] AccommodationItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccommodationItem {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ac;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool acc;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool acs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool aea;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool aes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool aph;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ams;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ppe;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool elec;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        public AccommodationItem() {
            this.ac = false;
            this.acc = false;
            this.acs = false;
            this.aea = false;
            this.aes = false;
            this.aph = false;
            this.ams = false;
            this.ppe = false;
            this.elec = false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PresentLevel {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MasteredGoal[] MasteredGoals;
        
        /// <remarks/>
        public GoalData GoalData;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PresentLevelSubject subject;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subjectSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MasteredGoal {
        
        /// <remarks/>
        public string Conditions;
        
        /// <remarks/>
        public string Behavior;
        
        /// <remarks/>
        public string Measure;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MasteredObjective", IsNullable=false)]
        public string[] MasteredObjectives;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GoalData {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Benchmark")]
        public Benchmark[] Benchmark;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Benchmark {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BenchmarkTest")]
        public BenchmarkTest[] BenchmarkTest;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime date;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BenchmarkTest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int correct;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool correctSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(18)]
        public int total;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BenchmarkRating rating;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ratingSpecified;
        
        public BenchmarkTest() {
            this.total = 18;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum BenchmarkRating {
        
        /// <remarks/>
        Mastery,
        
        /// <remarks/>
        Instructional,
        
        /// <remarks/>
        Emerging,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Review/Revise")]
        ReviewRevise,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum PresentLevelSubject {
        
        /// <remarks/>
        Reading,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Social Studies")]
        SocialStudies,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Written Expression")]
        WrittenExpression,
        
        /// <remarks/>
        Math,
        
        /// <remarks/>
        Science,
        
        /// <remarks/>
        Functional,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Social/Emotional")]
        SocialEmotional,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MasteredGoals {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MasteredGoal")]
        public MasteredGoal[] MasteredGoal;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MasteredObjectives {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MasteredObjective")]
        public string[] MasteredObjective;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class AccommodationsList {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccommodationCategory")]
        public AccommodationCategory[] AccommodationCategory;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PresentLevels {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PresentLevel")]
        public PresentLevel[] PresentLevel;
    }
}
